<a href="https://colab.research.google.com/github/Israel-San-Agustin/METODOS-NUMERICOS-/blob/main/Eliminaci%C3%B3n_gaussiana_con_pivoteo_parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pivoteo parcial

In [2]:
import numpy as np

def eliminacion_gaussiana_pivoteo_parcial(A):
    """
    Resolución de un sistema de ecuaciones lineales usando eliminación gaussiana con pivoteo parcial.

    Parámetros:
    A (numpy.ndarray): Matriz aumentada del sistema (n x n+1).

    Retorna:
    numpy.ndarray: Vector solución x si existe una solución única.
    """
    n = A.shape[0]  # Número de filas de la matriz A

    print("Matriz Aumentada Inicial:")
    print(A)

    # Proceso de Eliminación Gaussiana con Pivoteo Parcial
    for i in range(n):
        # Encontrar el mayor pivote absoluto en la columna actual
        max_row_index = np.argmax(abs(A[i:, i])) + i
        if A[max_row_index, i] == 0:
            raise ValueError("El sistema no tiene solución única (pivote nulo encontrado).")

        # Intercambiar la fila actual con la fila del mayor pivote
        if i != max_row_index:
            A[[i, max_row_index]] = A[[max_row_index, i]]

        # Eliminar los elementos debajo del pivote
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - factor * A[i, i:]

        # Imprimir la matriz después de la eliminación de cada columna
        print(f"\nMatriz después de la eliminación en la columna {i + 1}:")
        print(A)

    # Sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (A[i, -1] - np.dot(A[i, i + 1:n], x[i + 1:n])) / A[i, i]

    # Imprimir la matriz después de la sustitución hacia atrás
    print("\nMatriz reducida:")
    print(A)

    return x

# Ejemplo de uso
if __name__ == "__main__":
    # Definir la matriz aumentada del sistema
    A = np.array([[0.003000, 59.14, 59.17],
                  [5.291, -6.130, 46.78]], dtype=float)

    try:
        solucion = eliminacion_gaussiana_pivoteo_parcial(A)
        print("\nSolución del sistema:")
        for i in range(len(solucion)):
            print(f"x{i+1} = {solucion[i]:.6f}")
    except ValueError as e:
        print(e)


Matriz Aumentada Inicial:
[[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]]

Matriz después de la eliminación en la columna 1:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Matriz después de la eliminación en la columna 2:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Matriz reducida:
[[ 5.291      -6.13       46.78      ]
 [ 0.         59.14347571 59.14347571]]

Solución del sistema:
x1 = 10.000000
x2 = 1.000000
