<a href="https://colab.research.google.com/github/Israel-San-Agustin/METODOS-NUMERICOS-/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# $Factorización$ $LU$

Para factorizar la matriz $n X n$ $A$ = $[a_{ij}]$ en el producto de la matriz triangular inferior

$L$ = $[l_{i j}]$ y la matriz triangular superior $U$ = $[u_{i j}]$, es decir $A$ $LU$, donde la diagonal
principal ya sea de $L$ o $U$ consta sólo de unos:

In [8]:
import numpy as np

In [9]:
def lu_factorization(A):

    n = A.shape[0]  # Dimensión de la matriz
    L = np.eye(n)   # Inicializar L como la matriz identidad
    U = A.copy()    # Copiar A para modificar en U

    for j in range(n):
        # Verificar si el pivote es cero
        if U[j, j] == 0:
            raise ValueError("Factorización imposible: pivote cero en la posición ({}, {}).".format(j, j))

        # Actualizar las filas de U y L
        for i in range(j + 1, n):
            L[i, j] = U[i, j] / U[j, j]
            for k in range(j, n):
                U[i, k] -= L[i, j] * U[j, k]

    return L, U


In [10]:
def solve_lu(L, U, b):

    # Sustitución hacia adelante para resolver Ly = b
    n = L.shape[0]
    y = np.zeros_like(b, dtype=float)
    print("\nProceso de sustitución hacia adelante (Ly = b):")
    for i in range(n):
        y[i] = b[i] - sum(L[i, j] * y[j] for j in range(i))
        print(f"y[{i}] = {y[i]:.4f}")

    # Sustitución hacia atrás para resolver Ux = y
    x = np.zeros_like(b, dtype=float)
    print("\nProceso de sustitución hacia atrás (Ux = y):")
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(U[i, j] * x[j] for j in range(i + 1, n))) / U[i, i]
        print(f"x[{i}] = {x[i]:.4f}")

    return x

In [11]:
# Matriz de entrada
if __name__ == "__main__":
    # Matriz A y vector b del ejemplo
    A = np.array([[1, 1, 0, 3],
                  [2, 1, -1, 1],
                  [3, -1, -1, 2],
                  [-1, 2, 3, -1]], dtype=float)
    # Vector b
    b = np.array([4, 1, -3, 4], dtype=float)

    try:
        L, U = lu_factorization(A)
        print("Matriz L:")
        print(L)
        print("Matriz U:")
        print(U)

        # Resolver el sistema Ax = b
        x = solve_lu(L, U, b)
        print("\nSolución del sistema:")
        print(x)
    except ValueError as e:
        print(e)




Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]
Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Proceso de sustitución hacia adelante (Ly = b):
y[0] = 4.0000
y[1] = -7.0000
y[2] = 13.0000
y[3] = -13.0000

Proceso de sustitución hacia atrás (Ux = y):
x[3] = 1.0000
x[2] = 0.0000
x[1] = 2.0000
x[0] = -1.0000

Solución del sistema:
[-1.  2.  0.  1.]
