<a href="https://colab.research.google.com/github/Israel-San-Agustin/METODOS-NUMERICOS-/blob/main/Tutorial_de_Numpy_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librería Numpy

La librería NumPy es una biblioteca en Python utilizada principalmente para el cálculo numérico y el manejo de datos en forma de arreglos o matrices. NumPy facilita trabajar con grandes cantidades de datos de manera eficiente al ofrecer estructuras y operaciones optimizadas, como los arrays multidimensionales (similares a las matrices en matemáticas) y una serie de funciones matemáticas rápidas.

# ¿Para qué se usa NumPy?
NumPy es ampliamente usada en áreas de ciencia de datos, machine learning, análisis de datos, y simulaciones científicas, ya que permite manipular datos de manera eficiente y realizar cálculos complejos con una sintaxis sencilla.

In [2]:
#importamos la libreria Numpy
import numpy as np

Arreglos $(Arrays)$

Los arrays son estructuras clave en NumPy. Son similares a las listas de Python, pero más eficientes y con mayor funcionalidad.

In [3]:
# Crear un arreglo desde una lista
a = np.array([1, 2, 3])
print(a) #donde se imprime el arreglo a

# Crear un arreglo 2D (matriz)
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b) # donde se imprime el arreglo b

[1 2 3]
[[1 2 3]
 [4 5 6]]


Propiedades de los arreglos

In [4]:
print(a.shape)  # Tamaño del arreglo (3,)
print(b.shape)  # Tamaño del arreglo (2, 3)
print(a.ndim)   # Número de dimensiones (1)
print(b.ndim)   # Número de dimensiones (2)

(3,)
(2, 3)
1
2


Arreglos Comunes

NumPy proporciona funciones para crear arreglos predefinidos, útiles para inicializar arreglos rápidamente.

In [5]:
# Arreglo de ceros
zeros = np.zeros((2, 3))  # Matriz 2x3 de ceros

# Arreglo de unos
ones = np.ones((3, 3))  # Matriz 3x3 de unos

# Arreglo vacío (valores indefinidos, más rápido que zeros y ones)
empty = np.empty((2, 2))

# Arreglo con rango
rango = np.arange(10)    # 0 a 9
paso = np.arange(0, 10, 2)  # 0, 2, 4, 6, 8

# Arreglo con números igualmente espaciados
espacio = np.linspace(0, 1, 5)  # 0.0, 0.25, 0.5, 0.75, 1.0

print(zeros)
print(ones)
print(empty)
print(rango)
print(paso)
print(espacio)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5.04943414e-310 0.00000000e+000]
 [0.00000000e+000 1.38497710e+219]]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


Operaciones Básicas con Arreglos

NumPy permite hacer operaciones aritméticas de forma vectorizada, lo cual es rápido y directo.

In [6]:
# Suma y resta
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)

# Multiplicación y división elemento a elemento
print(a * b)
print(a / b)

# Potencias
print(a ** 2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


Funciones matemáticas

NumPy incluye funciones como $np.sqrt(), np.exp(), np.sin(), np.cos(), etc.$

In [7]:
sqrt_a = np.sqrt(a)  # Raíz cuadrada

In [8]:
# Raíz cuadrada
print(np.sqrt(a))  # [1. 1.41421356 1.73205081]

# Seno y coseno
print(np.sin(a))  # Seno de cada elemento de 'a'
print(np.cos(a))  # Coseno de cada elemento de 'a'

# Exponencial y logaritmo
print(np.exp(a))  # [2.71828183 7.3890561  20.08553692]
print(np.log(a))  # [0.         0.69314718 1.09861229]


[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


Álgebra Lineal

NumPy tiene funciones para álgebra lineal, que pueden ser muy útiles si trabajas con matrices.

In [9]:
# Producto punto (dot product)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b)) # Imprime la operacion entre las dos matrices


# Transpuesta
print(a.T)
# Donde imprime el valor de la transpuesta de a

# Transpuesta
print(b.T)
# Donde imprime el valor de la transpuesta de b


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


Indexación y Slicing

Indexación

Permite obtener elementos individuales de una secuencia. La indexación se basa en el número de índice o posición del elemento, y comienza en 0. Por ejemplo, el primer elemento de una secuencia tiene un índice de 0, el segundo de 1, y así sucesivamente.

Slicing

Permite extraer elementos de una secuencia, que pueden ser consecutivos o estar separados. La segmentación de cadenas se realiza con la sintaxis string[start:stop:step]. Esta sintaxis permite seleccionar caracteres desde el índice inicial hasta el índice final, sin incluirlo, con un paso opcional para omitir caracteres

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0, 0])  # Primer elemento (1)
print(a[0:2, 1:3])
# imprime el array


1
[[2 3]
 [5 6]]


Funciones de Estadística

NumPy ofrece muchas funciones de estadística sobre arreglos.

In [11]:
a = np.array([1, 2, 3, 4, 5])

print(np.mean(a))  # Media
print(np.std(a))   # Desviación estándar
print(np.var(a))   # Varianza
print(np.sum(a))   # Suma de todos los elementos
print(np.min(a))   # Mínimo
print(np.max(a))   # Máximo


3.0
1.4142135623730951
2.0
15
1
5


Manejo de Errores y Condiciones

In [12]:
a = np.array([1, 2, 3, 4, 5])

# Condición: seleccionar elementos mayores que 3
print(a[a > 3])  # [4 5]

# Asignar valor condicionalmente
a[a > 3] = 0
print(a)  # [1 2 3 0 0]


[4 5]
[1 2 3 0 0]


Ejemplo

In [13]:
# Creamos un arreglo de números
numeros = np.array([1, 2, 3, 4, 5])

# Calculamos la suma de los elementos
suma = np.sum(numeros)
print("Suma de los elementos:", suma)

# Calculamos la media (promedio) de los elementos
media = np.mean(numeros)
print("Media de los elementos:", media)


Suma de los elementos: 15
Media de los elementos: 3.0
